# Made by RandomHashTags
messages:
  purchase success:
  - "&aBought {AMOUNT}x {ITEM} for ${COST}"
  purchase success commands:
  - "&aBought {AMOUNT}x executed command(s) for ${COST}"
  purchase incomplete:
  - "&cYou don't have enough money!"
  purchase cancelled:
  - "&cYou've cancelled purchasing that item."
  not buyable:
  - "&cYou cannot purchase that item!"
  sell success:
  - "&aSold {AMOUNT}x {ITEM} for ${COST}"
  sell incomplete:
  - "&cYou don't have enough of that item!"
  sell cancelled:
  - "&cYou've cancelled selling that item."
  not sellable:
  - "&cThat item is not sellable!"
  #
  close due to reload:
  - "&eYou've exited this inventory due to the server reloading."
  #
  sell usage:
  - "&cUsage: &7/sell [chest/hand/inv]"
  must be looking at chest:
  - "&cYou must be looking at a chest to use this command!"
  need to be holding item:
  - "&cYou must be holding an item to sell!"
  cannot sell item to server:
  - "&cYou cannot sell this item to the server!"
  #
  no permission:
  - "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is an error."
#