name: Merchants
version: 14.5.0
main: me.randomhashtags.merchants.Merchants
author: RandomHashTags
api-version: 1.13
softdepend: [Citizens, Factions]
commands:
  merchants:
    usage: /merchants reload
    description: Reloads the plugin.
    permission: "Merchants.reload"
  sell:
    usage: /sell [hand/chest/inv]
    description: Sell items to the Merchants!
